version: "3.3"
services:
  mysql-device:
    image: mysql
    container_name: mysql-device
    restart: always
    environment:
      - MYSQL_USER=eimusername
      - MYSQL_PASSWORD=eimpassword
      - MYSQL_DATABASE=eim_database
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./volume/device:/var/lib/mysql

  mysql-profile:
    image: mysql
    container_name: mysql-profile
    restart: always
    environment:
      - MYSQL_USER=eimusername
      - MYSQL_PASSWORD=eimpassword
      - MYSQL_DATABASE=eim_database
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - ./volume/profile:/var/lib/mysql

  activemq:
    image: nexus.muc.ssdn.accounts.intern:40100/rmohr/activemq:latest
    container_name: activemq
    restart: always
    ports:
      - "8161:8161" # web interface
      - "9876:9876" # broker
      - "61616:61616"
