server.port: 8083

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true

com.eim.device-communication:
  default-operation-configuration:
    retries: 10
    timeout: 10
