server.port: 8082

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eim_database
    username: eimusername
    password: eimpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
