server.port: 8081

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eim_database
    username: eimusername
    password: eimpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true
